### ISSUE TITLE
Invalid Application: davidliuliuliu

### ISSUE THREAD

**Issue by drf-eng-apps** [dormroomfund/eng-apps#8]
Hey @davidliuliuliu, Your application is invalid! The reason is: challenge/run.sh exited with nonzero status 1

 output: 

 Hi! Launching python's simple webserver...
Here's a quote by Shakespeare while you wait:
"What's in a name? That which we call a rose by any other name would smell as sweet."
/home/travis/virtualenv/python3.6.2/bin/python: No module named SimpleHTTPServer

**Comment by drf-eng-apps** [comment]
Hey @davidliuliuliu, Your application is invalid! The reason is: **challenge/run.sh exited with nonzero status 1

 output: 

 Hi! Launching python's simple webserver...
Here's a quote by Shakespeare while you wait:
"What's in a name? That which we call a rose by any other name would smell as sweet."
/home/travis/virtualenv/python3.6.2/bin/python: No module named SimpleHTTPServer
**

**Comment by drf-eng-apps** [comment]
Hey @davidliuliuliu, Your application is invalid! The reason is: **challenge/run.sh did not output a URL with scheme http, https, ftp, or file

 output: 

 Hi! Launching python's simple webserver...
Here's a quote by Shakespeare while you wait:
"What's in a name? That which we call a rose by any other name would smell as sweet."
The webpage will be served at localhost:4863
**

**Comment by drf-eng-apps** [comment]
Hey @davidliuliuliu, Your application is invalid! The reason is: **challenge/run.sh timed out after 10 seconds - if you are starting a server, make sure you background it and print a URL**

**Comment by yasyf** [comment]
Sorry @davidliuliuliu, should be fixed now!

**Comment by drf-eng-apps** [comment]
Thanks @davidliuliuliu, your application has been fixed!
